
server:
  port: 8081

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/?characterEncoding=UTF-8
    username: root
    password: root


  sql:
    init:
      schema-locations: classpath:SQL/Init.sql
      mode: always
      platform: mysql

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.Entity

logging:
  level:
    root: info
    com.example.demo.Reposity: debug
  file:
    name: run.log
    path: ./

name: "YunfeiFu"
age: 23
balance: 100.00
birthday: 2012/12/12
isSuperUser: false
permissions: SuperUser,Vendor,B2B
ordered_Items: "{'iphone 14 Plus': '999.00','Mac Book bro': '2799.00'}"

orders:
  orderNo: 10000,
  itemName: Ipad Air
  itemPrice: 4999.00
  orderedDate: 2022/12/12
